apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: eds
spec:
  version: "PLACEHOLDER_TAG"
  shortDescription: Easily interact and manage ExtendedDaemonset resources.
  description: |
    The ExtendedDaemonset kubectl plugin provides useful utilities to operate daemonsets
    via the ExtendedDaemonset controller and the ExtendedDaemonset CRD.
  homepage: https://github.com/ahmed-mez/extendeddaemonset
  platforms:
  - uri: https://github.com/ahmed-mez/extendeddaemonset/releases/download/PLACEHOLDER_TAG/kubectl-eds_PLACEHOLDER_VERSION_darwin_arm64.zip
    sha256: "PLACEHOLDER_SHA_DARWIN_ARM"
    bin: kubectl-eds
    files:
    - from: kubectl-eds
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: darwin
        arch: arm64
